version: '3'

services:

  metal_price:
    build: ./api-server
    ports:
      - 3001:80
    depends_on:
      - currencysrv
      - metalsrv

  currencysrv:
    build: ./currency

  metalsrv:
    build: ./metal
