// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.3
// source: metal.proto

package metal

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// Meterials are the materials that can be priced.
type Materials int32

const (
	Materials_gold      Materials = 0
	Materials_silver    Materials = 1
	Materials_platinum  Materials = 2
	Materials_palladium Materials = 3
	Materials_copper    Materials = 4
	Materials_rhodium   Materials = 5
)

// Enum value maps for Materials.
var (
	Materials_name = map[int32]string{
		0: "gold",
		1: "silver",
		2: "platinum",
		3: "palladium",
		4: "copper",
		5: "rhodium",
	}
	Materials_value = map[string]int32{
		"gold":      0,
		"silver":    1,
		"platinum":  2,
		"palladium": 3,
		"copper":    4,
		"rhodium":   5,
	}
)

func (x Materials) Enum() *Materials {
	p := new(Materials)
	*p = x
	return p
}

func (x Materials) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Materials) Descriptor() protoreflect.EnumDescriptor {
	return file_metal_proto_enumTypes[0].Descriptor()
}

func (Materials) Type() protoreflect.EnumType {
	return &file_metal_proto_enumTypes[0]
}

func (x Materials) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Materials.Descriptor instead.
func (Materials) EnumDescriptor() ([]byte, []int) {
	return file_metal_proto_rawDescGZIP(), []int{0}
}

// MetalRequest defines the request for the GetPrice call.
type MetalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Metal is the metal for which the value is provided.
	Metal Materials `protobuf:"varint,1,opt,name=Metal,proto3,enum=metal.Materials" json:"Metal,omitempty"`
}

func (x *MetalRequest) Reset() {
	*x = MetalRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metal_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetalRequest) ProtoMessage() {}

func (x *MetalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metal_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetalRequest.ProtoReflect.Descriptor instead.
func (*MetalRequest) Descriptor() ([]byte, []int) {
	return file_metal_proto_rawDescGZIP(), []int{0}
}

func (x *MetalRequest) GetMetal() Materials {
	if x != nil {
		return x.Metal
	}
	return Materials_gold
}

// MetalResponse defines the response for the GetPrice call.
type MetalResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Price is the price of the metal.
	Price float64 `protobuf:"fixed64,1,opt,name=Price,proto3" json:"Price,omitempty"` // USD, per ounce
}

func (x *MetalResponse) Reset() {
	*x = MetalResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metal_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetalResponse) ProtoMessage() {}

func (x *MetalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metal_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetalResponse.ProtoReflect.Descriptor instead.
func (*MetalResponse) Descriptor() ([]byte, []int) {
	return file_metal_proto_rawDescGZIP(), []int{1}
}

func (x *MetalResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

var File_metal_proto protoreflect.FileDescriptor

var file_metal_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x6d, 0x65, 0x74, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6d,
	0x65, 0x74, 0x61, 0x6c, 0x22, 0x36, 0x0a, 0x0c, 0x4d, 0x65, 0x74, 0x61, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x05, 0x4d, 0x65, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x6c, 0x2e, 0x4d, 0x61, 0x74, 0x65,
	0x72, 0x69, 0x61, 0x6c, 0x73, 0x52, 0x05, 0x4d, 0x65, 0x74, 0x61, 0x6c, 0x22, 0x25, 0x0a, 0x0d,
	0x4d, 0x65, 0x74, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x50, 0x72,
	0x69, 0x63, 0x65, 0x2a, 0x57, 0x0a, 0x09, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x73,
	0x12, 0x08, 0x0a, 0x04, 0x67, 0x6f, 0x6c, 0x64, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x73, 0x69,
	0x6c, 0x76, 0x65, 0x72, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x69, 0x6e,
	0x75, 0x6d, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x70, 0x61, 0x6c, 0x6c, 0x61, 0x64, 0x69, 0x75,
	0x6d, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x63, 0x6f, 0x70, 0x70, 0x65, 0x72, 0x10, 0x04, 0x12,
	0x0b, 0x0a, 0x07, 0x72, 0x68, 0x6f, 0x64, 0x69, 0x75, 0x6d, 0x10, 0x05, 0x32, 0x3e, 0x0a, 0x05,
	0x4d, 0x65, 0x74, 0x61, 0x6c, 0x12, 0x35, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x50, 0x72, 0x69, 0x63,
	0x65, 0x12, 0x13, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x6c, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x6c, 0x2e, 0x4d,
	0x65, 0x74, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x09, 0x5a, 0x07,
	0x2e, 0x3b, 0x6d, 0x65, 0x74, 0x61, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_metal_proto_rawDescOnce sync.Once
	file_metal_proto_rawDescData = file_metal_proto_rawDesc
)

func file_metal_proto_rawDescGZIP() []byte {
	file_metal_proto_rawDescOnce.Do(func() {
		file_metal_proto_rawDescData = protoimpl.X.CompressGZIP(file_metal_proto_rawDescData)
	})
	return file_metal_proto_rawDescData
}

var file_metal_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_metal_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_metal_proto_goTypes = []interface{}{
	(Materials)(0),        // 0: metal.Materials
	(*MetalRequest)(nil),  // 1: metal.MetalRequest
	(*MetalResponse)(nil), // 2: metal.MetalResponse
}
var file_metal_proto_depIdxs = []int32{
	0, // 0: metal.MetalRequest.Metal:type_name -> metal.Materials
	1, // 1: metal.Metal.GetPrice:input_type -> metal.MetalRequest
	2, // 2: metal.Metal.GetPrice:output_type -> metal.MetalResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_metal_proto_init() }
func file_metal_proto_init() {
	if File_metal_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_metal_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetalRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_metal_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetalResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_metal_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_metal_proto_goTypes,
		DependencyIndexes: file_metal_proto_depIdxs,
		EnumInfos:         file_metal_proto_enumTypes,
		MessageInfos:      file_metal_proto_msgTypes,
	}.Build()
	File_metal_proto = out.File
	file_metal_proto_rawDesc = nil
	file_metal_proto_goTypes = nil
	file_metal_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MetalClient is the client API for Metal service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MetalClient interface {
	// GetValue provides the price of the metal.
	GetPrice(ctx context.Context, in *MetalRequest, opts ...grpc.CallOption) (*MetalResponse, error)
}

type metalClient struct {
	cc grpc.ClientConnInterface
}

func NewMetalClient(cc grpc.ClientConnInterface) MetalClient {
	return &metalClient{cc}
}

func (c *metalClient) GetPrice(ctx context.Context, in *MetalRequest, opts ...grpc.CallOption) (*MetalResponse, error) {
	out := new(MetalResponse)
	err := c.cc.Invoke(ctx, "/metal.Metal/GetPrice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetalServer is the server API for Metal service.
type MetalServer interface {
	// GetValue provides the price of the metal.
	GetPrice(context.Context, *MetalRequest) (*MetalResponse, error)
}

// UnimplementedMetalServer can be embedded to have forward compatible implementations.
type UnimplementedMetalServer struct {
}

func (*UnimplementedMetalServer) GetPrice(context.Context, *MetalRequest) (*MetalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPrice not implemented")
}

func RegisterMetalServer(s *grpc.Server, srv MetalServer) {
	s.RegisterService(&_Metal_serviceDesc, srv)
}

func _Metal_GetPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetalServer).GetPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metal.Metal/GetPrice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetalServer).GetPrice(ctx, req.(*MetalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Metal_serviceDesc = grpc.ServiceDesc{
	ServiceName: "metal.Metal",
	HandlerType: (*MetalServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPrice",
			Handler:    _Metal_GetPrice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "metal.proto",
}
